<?php

/**
 * @file
 * Contains glenville_oracle.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

const GLENVILLE_ORACLE_REMOTE_URL = 'https://thunderbird.glenville.edu:8888';

/**
 * Implements hook_help().
 */
function glenville_oracle_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the glenville_oracle module.
    case 'help.page.glenville_oracle':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module to connect, display, and pdf download course information') . '</p>';
      return $output;

    default:
  }
}
